[build]
  publish = "src/public"
  command = ""

[build.environment]
  NPM_FLAGS = "--ignore-scripts"

[[headers]]
  for = "/booking-ui/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "frame-ancestors *"
